### ISSUE TITLE
Command not found.

### ISSUE THREAD

**Issue by sudis** [ricardomaia/ghost#25]
Hello! I rolled up my sleeves to use your awesome Status page. Although I succeeded in many things, I got stuck in the `nom publish` part at the end.

To simply describe what I did;

1- Forking Repo
2- `npm install`
3- `node setup.js` (Key+)
4- `npm run dev` (Localhost is running.)
5- `npm run build` Heres log:

```
laevaintain@MacBook-Pro ghost % npm run build

> page-status@0.0.1 build
> rollup -c


src/main.js → public/build/bundle.js...
created public/build/bundle.js in 3.5s
```

6- `npm run publish` Heres log too:

```
laevaintain@MacBook-Pro ghost % npm run publish

> page-status@0.0.1 publish
> npm run build && node_modules\.bin\gh-pages.cmd -d public


> page-status@0.0.1 build
> rollup -c


src/main.js → public/build/bundle.js...
created public/build/bundle.js in 3.5s
sh: node_modules.bingh-pages.cmd: command not found
```

I would be very happy if you tell me what to do.

Sincerely, 
Magdalena Sude.

**Comment by ricardomaia** [comment]
Forgive me sudis. I didn't see your message notification.

Probbaly this issue is related to your MacOS environment.

In the package.json file, modify the publish scrip to `"publish": "npm run build && node_modules/.bin/gh-pages -d public"`

**Comment by ricardomaia** [comment]
I hope I fixed this problem in the last commit. https://github.com/ricardomaia/ghost/commit/e98ea9f1f7fb4e91529fb7843a014c7da5bef0e4
